In [ ]:
Numpy and Pandas, EDA and Dashborad
Data collected can have problems of 1. missing data, 2. Unnecessary data , 3. wrong data , wrong format 
trainig machine for preparing pizza

In [1]:
!pip install numpy



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
import numpy as np
a = np.arange(24)
print(a)

b = a.reshape(2,4,3)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [6]:
# Task 1: There are 5 students with height and weight.Calculate Bmi of all 5 students.

In [10]:
import numpy as np

# Heights(meters)
heights = np.array([1.50, 1.55, 1.60, 1.65, 1.70])  

# Weights(kilograms)
weights = np.array([50, 60, 70, 80, 85])  

# BMI Formula
bmi = weights / (heights ** 2)

print(bmi)


[22.22 24.97 27.34 29.38 29.41]


In [ ]:
#Milestone 1: Download the data set for Forecasting Air Quality Using 
#Historical Pollution Data. Then do data preprocessing & EDA